const newRules = [
    "RULE-SET,ZJU,✔ ZJU内网",
    "RULE-SET,ZJU-More-Scholar,📃 ZJU More Scholar",
    "RULE-SET,LocalAreaNetwork,🎯 全球直连",
    "RULE-SET,UnBan,🎯 全球直连",
    "RULE-SET,GoogleCN,🎯 全球直连",
    "RULE-SET,SteamCN,🎯 全球直连",
    "RULE-SET,Adobe,🎯 全球直连",
    "RULE-SET,PrivateTracker,🎯 全球直连",
    "RULE-SET,ChinaIp,🎯 全球直连",
    "RULE-SET,ChinaDomain,🎯 全球直连",
    "RULE-SET,ChinaCompanyIp,🎯 全球直连",
    "RULE-SET,Download,🎯 全球直连",
    "GEOIP,CN,DIRECT",
    "GEOIP,CN,DIRECT",
    "RULE-SET,BanAD,🛑 广告拦截",
    "RULE-SET,BanProgramAD,🍃 应用净化",
    "RULE-SET,BanEasyList,🆎 AdBlock",
    "RULE-SET,BanEasyListChina,🆎 AdBlock",
    "RULE-SET,BanEasyPrivacy,🛡️ 隐私防护",
    "RULE-SET,GoogleFCM,📢 谷歌FCM",
    "RULE-SET,OneDrive,Ⓜ️ 微软云盘",
    "RULE-SET,Microsoft,Ⓜ️ 微软服务",
    "RULE-SET,Apple,🍎 苹果服务",
    "RULE-SET,Telegram,📲 电报消息",
    "RULE-SET,NetEaseMusic,🎶 网易音乐",
    "RULE-SET,Epic,🎮 游戏平台",
    "RULE-SET,Sony,🎮 游戏平台",
    "RULE-SET,Steam,🎮 游戏平台",
    "RULE-SET,Nintendo,🎮 游戏平台",
    "RULE-SET,YouTube,📹 油管视频",
    "RULE-SET,Netflix,🎥 奈飞视频",
    "RULE-SET,Bahamut,📺 巴哈姆特",
    "RULE-SET,BilibiliHMT,📺 哔哩哔哩",
    "RULE-SET,Bilibili,📺 哔哩哔哩",
    "RULE-SET,ChinaMedia,🌏 国内媒体",
    "RULE-SET,ProxyMedia,🌍 国外媒体",
    "RULE-SET,ProxyGFWlist,🚀 节点选择",
    "MATCH,🐟 漏网之鱼",
];